--REFERENTIAL INTEGRITY

DROP TABLE EMOLOYEES;
DROP TABLE DEPARTMENTS;

-- CREATING A PARENT TABLE
CREATE TABLE DEPARTMENTS(
dept_id INT PRIMARY KEY,
dept_Name VARCHAR(50) NOT NULL
);

--INSERTING VALUES INTO THE PARENT TABLE
INSERT INTO DEPARTMENTS VALUES
(1,'HR'),(2,'IT'),(3,'FIN'),(4,'QA');

-- CREATING THE CHILD TABLE
CREATE TABLE EMOLOYEES(
emp_id INT PRIMARY KEY,
Name VARCHAR(50) UNIQUE,
dept_id INT FOREIGN KEY REFERENCES DEPARTMENTS(dept_id),
email VARCHAR(50) DEFAULT 'company@email.com',
Age INT CHECK(age>21)
);

--INSERTING VALUES INTO THE CHILD TABLE
INSERT INTO EMOLOYEES VALUES (1,'AB',1,'AB@evry.com',22),
(2,'CD',3,'CD@evry.com',22),
(4,'EF',3,'EF@evry.com',23);

INSERT INTO EMOLOYEES (emp_id,name,dept_id,age) VALUES (3,'GH',4,25);

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMOLOYEES;


-- REFERENTIAL INTEGRITY WITH CASCADE
ALTER TABLE EMOLOYEES  DROP CONSTRAINT FK__EMOLOYEES__dept___5FB337D6;

ALTER TABLE EMOLOYEES ADD CONSTRAINT FK_emp_dept_id FOREIGN KEY (dept_id) 
REFERENCES DEPARTMENTS(dept_id) ON DELETE CASCADE ON UPDATE CASCADE;

DELETE FROM DEPARTMENTS WHERE dept_id=3;

UPDATE DEPARTMENTS SET dept_id=3 WHERE dept_Name='QA';
 

ALTER TABLE EMOLOYEES
ADD CONSTRAINT df_constraint DEFAULT 1 FOR dept_id;

INSERT INTO EMOLOYEES (emp_id,name,email,age) VALUES (5,'IJ','IJ@gmail.com',25);

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMOLOYEES;

ALTER TABLE EMOLOYEES  DROP CONSTRAINT FK__EMOLOYEES__dept___68487DD7;

ALTER TABLE EMOLOYEES ADD CONSTRAINT FK_emp_dept_id FOREIGN KEY (dept_id) 
REFERENCES DEPARTMENTS(dept_id) ON DELETE SET DEFAULT ON UPDATE SET DEFAULT;

DELETE FROM DEPARTMENTS WHERE dept_id=3;

UPDATE DEPARTMENTS SET dept_id=3 WHERE dept_Name='QA';
 
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMOLOYEES;